import React, {useState} from "react";

// Components
import {CommonButton} from "../components/Button.jsx"

// Utils
import generateRandomArray from "../utils/generateRandomArray.js"

const RandomArrayGenerator = ({ onData }) => {
  const [inputArray, setInputArray] = useState([]);

  const handleInputChange = (event) => {
    event.preventDefault();
    const inputValue = event.target.value;
    const parsedArray = inputValue.split(', ').map((item) => {
      const parsedValue = Number(item);
      if (!isNaN(parsedValue)) {
        return parsedValue;
      } else {
        return null;
      }
    }).filter(value => value !== null);

    setInputArray(parsedArray.length ? parsedArray : generateRandomArray(1000, 10000));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const finalArray = inputArray.length ? inputArray : generateRandomArray(1000, 10000);
    setInputArray(finalArray);
    onData(finalArray);
  }

  return (
    <div>
      <form onSubmit={handleSubmit}>
        <textarea
          type="text" 
          placeholder="Enter custom array values" 
          onChange={handleInputChange} 
          className="bg-gray-50 border border-light-cyan text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-marian-blue block w-full p-2.5"
        />
        <CommonButton type="submit" label="Submit" />
      </form>
      <p>
        <b>Note:</b> If you enter a custom array, the syntax should be a number followed by a comma and space before entering the next number.
        <b> Example:</b> 1, 2, 3. Otherwise, the array will be auto-generated by the system.
      </p>
    </div>
  );
};

export default RandomArrayGenerator;